engines:
  pep8:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - python:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.py"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- "app/static/css/materialize.css"
- "app/static/js/materialize.js"